### PR TITLE
update 2x submodules, change implementation of USE_LOCAL_CC65

### PR DESCRIPTION
**Pull request by Ben-401**
done. Still working through the dependancies on stable_base.

### CODE REVIEW

**Comment by Ben-401** [comment]
this PR is ready to merge in, at the moment branch stable_base does not build from clean checkout.
after merging this PR (as the submodules have already been updated), the stable_base will compile from a clean checkout.

**Comment by frehwagen** [comment]
Isn't it, that keeping this unchanged in the Makefile:

```
$(SDCARD_DIR)/FREEZER.M65:
	git submodule init
	git submodule update
	( cd src/mega65-freezemenu && make FREEZER.M65 USE_LOCAL_CC65=$(USE_LOCAL_CC65))
	cp src/mega65-freezemenu/FREEZER.M65 $(SDCARD_DIR)
```

still always defines "USE_LOCAL_CC65=" for the submodules and this is not the way it is not supported anymore?

**Comment by Ben-401** [comment]
@frehwagen thanks for look at that.
Have you tried both with and without the "USE_LOCAL_CC65=1" and if so on what O/S?

I have tried both ubuntu 16 and 18 and both of those O/S implement the logic correct.
I will paste below the output.

**Comment by Ben-401** [comment]
```
     1  t2@t2-VirtualBox:~/dev/ben-401/mega65-core$ make sdcard-files/FREEZER.M65
     2  Makefile:80: =============================================================
     3  Makefile:80: ~~~~~~~~~~~~~~~~> Making: sdcard-files/FREEZER.M65
     4  git submodule init
     5  git submodule update
     6  ( cd src/mega65-freezemenu && make FREEZER.M65 USE_LOCAL_CC65=)
     7  make[1]: Entering directory '/home/t2/dev/ben-401/mega65-core/src/mega65-freezemenu'
     8  Makefile:73: ======== Making: freezer.s
     9  cc65/bin/cc65 -t c64 -Os --cpu 65c02 -Icc65/include -o freezer.s freezer.c
    10  freezer.c(243): Warning: Parameter `msg' is never used
    11  freezer.c(400): Warning: Converting pointer to integer without a cast
    12  freezer.c(400): Warning: Converting pointer to integer without a cast
    13  freezer.c(401): Warning: Converting pointer to integer without a cast
<snip>
    33  freezer.c(438): Warning: Converting pointer to integer without a cast
    34  freezer.c(438): Warning: Converting pointer to integer without a cast
    57  freezer.c(992): Warning: Converting pointer to integer without a cast
    58  freezer.c(996): Warning: Converting pointer to integer without a cast
    59  Makefile:73: ======== Making: frozen_memory.s
    60  cc65/bin/cc65 -t c64 -Os --cpu 65c02 -Icc65/include -o frozen_memory.s frozen_memory.c
    61  Makefile:73: ======== Making: freeze_monitor.s
    62  cc65/bin/cc65 -t c64 -Os --cpu 65c02 -Icc65/include -o freeze_monitor.s freeze_monitor.c
    63  Makefile:73: ======== Making: freeze_diskchooser.s
    64  cc65/bin/cc65 -t c64 -Os --cpu 65c02 -Icc65/include -o freeze_diskchooser.s freeze_diskchooser.c
    65  freeze_diskchooser.c(107): Warning: Converting pointer to integer without a cast
    66  freeze_diskchooser.c(117): Warning: Converting pointer to integer without a cast
    67  freeze_diskchooser.c(239): Warning: Converting pointer to integer without a cast
    68  freeze_diskchooser.c(285): Warning: Converting pointer to integer without a cast
    69  freeze_diskchooser.c(288): Warning: Converting pointer to integer without a cast
    70  freeze_diskchooser.c(292): Warning: Converting pointer to integer without a cast
    71  freeze_diskchooser.c(303): Warning: Result of comparison is constant
    72  freeze_diskchooser.c(350): Warning: Converting pointer to integer without a cast
    73  Makefile:73: ======== Making: fdisk_memory.s
    74  cc65/bin/cc65 -t c64 -Os --cpu 65c02 -Icc65/include -o fdisk_memory.s fdisk_memory.c
    75  fdisk_memory.c(47): Warning: `i' is defined but never used
    76  Makefile:73: ======== Making: fdisk_screen.s
    77  cc65/bin/cc65 -t c64 -Os --cpu 65c02 -Icc65/include -o fdisk_screen.s fdisk_screen.c
    78  Makefile:73: ======== Making: fdisk_fat32.s
    79  cc65/bin/cc65 -t c64 -Os --cpu 65c02 -Icc65/include -o fdisk_fat32.s fdisk_fat32.c
    80  Makefile:73: ======== Making: fdisk_hal_mega65.s
    81  cc65/bin/cc65 -t c64 -Os --cpu 65c02 -Icc65/include -o fdisk_hal_mega65.s fdisk_hal_mega65.c
    82  Makefile:107: ======== Making: FREEZER.M65
    83  cc65/bin/cl65 -t c64 -Os --cpu 65c02 -Icc65/include --asm-include-dir cc65/asminc --cfg-path cc65/cfg --lib-path cc65/lib -vm -m freezer.map -o FR$
    84  ld65: Warning: Duplicate external identifier: `_i'
    85  make[1]: Leaving directory '/home/t2/dev/ben-401/mega65-core/src/mega65-freezemenu'
    86  cp src/mega65-freezemenu/FREEZER.M65 sdcard-files
    87  t2@t2-VirtualBox:~/dev/ben-401/mega65-core$ cd src/mega65-freezemenu/ && make clean && cd ../..
    88  rm -f FREEZER.M65 AUDIOMIX.M65 SPRITED.M65 C65THUMB.M65 C64THUMB.M65 GUSTHUMB.M65 *.o \
    89  audiomix.s \
    90  freeze_*.s \
    91  frozen_memory.s \
    92  fdisk_*.s \
    93  freezer.s sprited.s \
    94  *.map \
    95  ascii.h ascii8x8.bin asciih \
    96  pngprepare \
    97  tools/thumbnail-surround-formatter
    98  t2@t2-VirtualBox:~/dev/ben-401/mega65-core$

**Comment by Ben-401** [comment]
```
    98  t2@t2-VirtualBox:~/dev/ben-401/mega65-core$ make sdcard-files/FREEZER.M65 USE_LOCAL_CC65=1
    99  Makefile:80: =============================================================
   100  Makefile:80: ~~~~~~~~~~~~~~~~> Making: sdcard-files/FREEZER.M65
   101  git submodule init
   102  git submodule update
   103  ( cd src/mega65-freezemenu && make FREEZER.M65 USE_LOCAL_CC65=1)
   104  make[1]: Entering directory '/home/t2/dev/ben-401/mega65-core/src/mega65-freezemenu'
   105  Makefile:96: ======== Making: asciih
   106  cc -o asciih asciih.c
   107  Makefile:99: ======== Making: ascii.h
   108  ./asciih
   109  Makefile:103: ======== Making: pngprepare
   110  cc -I/usr/local/include -L/usr/local/lib -o pngprepare pngprepare.c -lpng
   111  Makefile:92: ======== Making: ascii8x8.bin
   112  ./pngprepare charrom ascii00-7f.png ascii8x8.bin
   113  argv[0]=./pngprepare
   114  argv[1]=charrom
   115  argv[2]=ascii00-7f.png
   116  argv[3]=ascii8x8.bin
   117  Reading ascii00-7f.png
   118  Input-file is: width=8, height=2048.
   119  Input-file is read and now closed
   120  Processing with mode=1 and output=ascii8x8.bin
   121  mode=1 (charrom)
   122  done
   123  Makefile:73: ======== Making: freezer.s
   124  cc65 -t c64 -Os --cpu 65c02 -Icc65/include -o freezer.s freezer.c
   125  freezer.c(243): Warning: Parameter `msg' is never used
   126  freezer.c(400): Warning: Converting pointer to integer without a cast
   127  freezer.c(400): Warning: Converting pointer to integer without a cast
   128  freezer.c(401): Warning: Converting pointer to integer without a cast
   129  freezer.c(401): Warning: Converting pointer to integer without a cast
   130  freezer.c(403): Warning: Converting pointer to integer without a cast
<snip>
   171  freezer.c(504): Warning: Converting pointer to integer without a cast
   172  freezer.c(992): Warning: Converting pointer to integer without a cast
   173  freezer.c(996): Warning: Converting pointer to integer without a cast
   174  Makefile:73: ======== Making: frozen_memory.s
   175  cc65 -t c64 -Os --cpu 65c02 -Icc65/include -o frozen_memory.s frozen_memory.c
   176  Makefile:73: ======== Making: freeze_monitor.s
   177  cc65 -t c64 -Os --cpu 65c02 -Icc65/include -o freeze_monitor.s freeze_monitor.c
   178  Makefile:73: ======== Making: freeze_diskchooser.s
   179  cc65 -t c64 -Os --cpu 65c02 -Icc65/include -o freeze_diskchooser.s freeze_diskchooser.c
   180  freeze_diskchooser.c(107): Warning: Converting pointer to integer without a cast
   181  freeze_diskchooser.c(117): Warning: Converting pointer to integer without a cast
   182  freeze_diskchooser.c(239): Warning: Converting pointer to integer without a cast
   183  freeze_diskchooser.c(285): Warning: Converting pointer to integer without a cast
   184  freeze_diskchooser.c(288): Warning: Converting pointer to integer without a cast
   185  freeze_diskchooser.c(292): Warning: Converting pointer to integer without a cast
   186  freeze_diskchooser.c(303): Warning: Result of comparison is constant
   187  freeze_diskchooser.c(350): Warning: Converting pointer to integer without a cast
   188  Makefile:73: ======== Making: fdisk_memory.s
   189  cc65 -t c64 -Os --cpu 65c02 -Icc65/include -o fdisk_memory.s fdisk_memory.c
   190  fdisk_memory.c(47): Warning: `i' is defined but never used
   191  Makefile:73: ======== Making: fdisk_screen.s
   192  cc65 -t c64 -Os --cpu 65c02 -Icc65/include -o fdisk_screen.s fdisk_screen.c
   193  Makefile:73: ======== Making: fdisk_fat32.s
   194  cc65 -t c64 -Os --cpu 65c02 -Icc65/include -o fdisk_fat32.s fdisk_fat32.c
   195  Makefile:73: ======== Making: fdisk_hal_mega65.s
   196  cc65 -t c64 -Os --cpu 65c02 -Icc65/include -o fdisk_hal_mega65.s fdisk_hal_mega65.c
   197  Makefile:107: ======== Making: FREEZER.M65
   198  cl65 -t c64 -Os --cpu 65c02 -Icc65/include --asm-include-dir cc65/asminc --cfg-path cc65/cfg --lib-path cc65/lib -vm -m freezer.map -o FREEZER.M65$
   199  ld65: Warning: Duplicate external identifier: `_i'
   200  make[1]: Leaving directory '/home/t2/dev/ben-401/mega65-core/src/mega65-freezemenu'
   201  cp src/mega65-freezemenu/FREEZER.M65 sdcard-files
   202  t2@t2-VirtualBox:~/dev/ben-401/mega65-core$

**Comment by Ben-401** [comment]
in the above, line 1 and line 6 show that I want to build the submodule of mega65-freezer.
lines 9, 60, 62 show that the submodule is being used. (submodule didnt need making)
after line 86, the target was built using the submodule.

lines 87 down, i cleared that target.

line 98 I asked for the LOCAL to be used, by specifying "USE_LOCAL_CC65=1" on the CLI.
lines 124, 175 show the LOCAL being used, 

So, sorry, I cannot see where I went wrong, can you please identify?

**Comment by Ben-401** [comment]
lines 6 and 103 show the different makefile cases, both seem ok to me.

Yes although line 6 uses "USE_LOCAL_CC65=" (ie with no "1"),
the submodules Makefile considered this as a fail in the ifdef, causing the sub-submodule to be used.

**Comment by frehwagen** [comment]
Thx for double checking, my question was more theoretically. Good to know 'USE_LOCAL_CC65=""' actually means undefine. I'm on windows backed Jenkins. Will merge it now.

**Pull request merged**
