### PR TITLE
Make bit2core compile under Windows

### PR DESCRIPTION
**Pull request by deftmega**
...and added a version number :)

### CODE REVIEW

**Comment by gardners** [comment]
hmm.. I don't think you really meant to change 286 files in the process.  Let me find the correct one.
Meanwhile, I am thinking that I am going to split out all these cross-platform tools into a separate repo, so that they are easier to build and maintain.

**Comment by gardners** [comment]
I'm including the fixes to bit2core in the hyperram feature branch 165-hyperram for #165

**Comment by gardners** [comment]
I think we fixed this already, right?

**Comment by deftmega** [comment]
Re: [MEGA65/mega65-core] Make bit2core compile under Windows (#187)


Guten Tag gardners,

am Freitag, 12. Juni 2020 um 01:16 schrieben Sie:





I think we fixed this already, right?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



yes!

-- 
Mit freundlichen Grüßen
Detlef Hastik [MEGA Museum of Electronic Games & Art]
mailto:deft@m-e-g-a.org

**Comment by gurcei** [comment]
Feel like this ticket is sorted now, bit2core is automatically building for windows & linux on the mega65-tools 'releases' page here for every new commit/merge made to master branch:

- https://github.com/MEGA65/mega65-tools/releases/tag/CI-latest

**Comment by gardners** [comment]
Since dealt with in the mega65-tools repo

**Pull request closed without merging**
