### PR TITLE
Replaced "c65gs" references with "MEGA65"

### PR DESCRIPTION
**Pull request by gurcei**
Did a sed and did a manual sanity-check look over the changes. I didn't get a chance to tinker with the Makefile ideas you had yet, might have to save that for another occasion.

### CODE REVIEW

**Comment by gurcei** [comment]
I noticed that my fork of the repo had some repairs to the documentation relating to the change in product name (from c65gs to MEGA65). I think at some stage you requested me to make this change, but I forgot to make a pull-request to drop it back in the upstream repo. So thought I'd better try that now. I did apply the change to the master branch at the time, probably because I didn't know any better. Hopefully that's ok, but let me know if it isn't, and I'll try wrestle with git some more to figure out how to drop it in a better home.

**Comment by gurcei** [comment]
Ah wait, it looks like I did make a pull-request in the past relating to this, but it never got approved/rejected so it just got left dangling in github, methinks.

**Comment by Ben-401** [comment]
I tried to imcorporate that change but i dont have the permissions. Only paul, me thinks.

**Comment by gardners** [comment]
Hello,

Please send me the URL for the pull request, and I will take a look.

Paul.

**Comment by gurcei** [comment]
Yup sure, here's the URL:

https://github.com/MEGA65/mega65-core/pull/16

Gurce

**Pull request merged**
