### PR TITLE
TCL constraints

### PR DESCRIPTION
**Pull request by amb5l**
Add SDRAM etc timing recipe to this for a better future!

### CODE REVIEW

**Comment by lydon42** [comment]
Hmmm, we already merged the mega65r4-bringup branch, but @gardners  seems not to have merged this PR.

Do we still need it or was it integrated in a different way?

**Comment by amb5l** [comment]
@gardners agreed that this was a reasonable way to bring in the  TCL constraints recipe (and add me as a contributor!).

**Comment by lydon42** [comment]
Ok, then I will merge them to development.

**Comment by lydon42** [comment]
For me it looks like this is not really used. The four lines at the end always throw an error, but they don't do this if I build with your changes.
Does this need to be referenced in some way? I can see that the mega65r4_gen.tcl mentions mega65r4.tcl, but without a path:
```
variable script_file
set script_file "mega65r4.tcl"
```

So am I really testing with the change or is this just for reference?

**Pull request closed without merging**
