### PR TITLE
Implemented trap_dos_writefile and trap_dos_rmfile

### PR DESCRIPTION
**Pull request by MirageBD**
Implemented trap_dos_writefile.

### CODE REVIEW

**Comment by MirageBD** [comment]
Added trap_dos_rmfile to same PR.

**Comment by MirageBD** [comment]
Adding implementation of fstat.

**Comment by lydon42** [comment]
I will close this PR, as we decided to implement this after Batch 3 release into a separate branch (named `760-dos-hyppo`), so release is not delayed by it.

**Comment by lydon42** [comment]
Closing it was not a good idea (note to myself). And as nobody really worked on 760, there was also no work done here. So better keep it open so we don't miss!

**Comment by lydon42** [comment]
I think we could evaluate if merging into development now is possible. If yes we should do it.

**Review by lydon42 — APPROVED** [review]
Looks good.

**Comment by lydon42** [comment]
Merged into 760-hyppo-dos13

**Comment by lydon42** [comment]
its merged into 760-hyppo-dos13, so now we can close it for real.

**Comment by MirageBD** [comment]
Thank you :) Here comes the highscore saving for firstshot, hopefully

**Pull request closed without merging**
